baseurl = "https://kent.network/"
title = "Kent.Network"
languageCode = "en-gb"
theme = "KentNetwork"


[menu]
    [[menu.main]]
    name = "Kent.Network"
    pre = "/images/logo/logo.svg"
    weight = 1
    identifier = "home"
    url = "/"

    [[menu.main]]
    name = "Network"
    weight = 2
    identifier = "network"
    url = "/network/about/"

    [[menu.main]]
    name = "Services"
    weight = 3
    identifier = "services"
    url = "/services/about/"

    [[menu.main]]
    name = "About"
    weight = 5
    identifier = "about"
    url = "/about/"

    [[menu.main]]
    name = "Flood Detection"
    parent = "services"
    url = "https://flood.kent.network/"
